spring:
  redis:
    #    password: '@191125!#'
    database: 3
    #    host: edu-redis
    #    port: 6379
    host: redis
    port: 6379
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: edu-auth-xiao
          uri: lb://edu-auth-xiao
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #UPMS 模块
        - id: edu-system-xiao
          uri: lb://edu-system-xiao
          predicates:
            - Path=/admin/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # 代码生成模块
        - id: edu-codegen
          uri: lb://edu-codegen
          predicates:
            - Path=/gen/**
      # bus中心
        - id: edu-bus-xiao
          uri: lb://edu-bus-xiao
          predicates:
          - Path=/bus/**
        # bus中心
        - id: edu-mobile-xiao
          uri: lb://edu-mobile-xiao
          predicates:
            - Path=/mobile/**

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'eduedu,edu1cloud'
  oauth2:
    resource:
      loadBalanced: true
      token-info-uri: http://edu-auth-xiao/oauth/check_token
# 不校验验证码终端
ignore:
  clients:
    - test
    - systest/page
