security:
  oauth2:
    client:
     #client-id: ENC(imENTO7M8bLO38LFSIxnzw==)
    #      #client-secret: ENC(i3cDFhs26sa2Ucrfz2hnQw==)
      client-id: ENC(CQBV16FI6KdU4OJmfDP+kg==)
      client-secret: ENC(CQBV16FI6KdU4OJmfDP+kg==)
      scope: server
    resource:
      loadBalanced: true
      token-info-uri: http://edu-auth-chu/oauth/check_token

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: (%3zH&!&c/Lp;3x+TL
#    url: jdbc:mysql://edu-mysql:3306/edu_xiao?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    password: vankia@123!
#    url: jdbc:mysql://39.98.34.83:8880/edu_xiao?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    password: (%3zH&!&c/Lp;3x+TL
    url: jdbc:mysql://mysql:3306/edu_chu?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    #    password: '@191125!#'
    database: 2
    #    host: edu-redis
    #    port: 6379
    host: redis
    port: 6379
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 10MB #最大请求文件的大小
      max-file-size: 10MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
# 直接放行URL(但必须经过网关)
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /parentRegister/**
    - /screen/**
    - /screenchild/**
    - /screenBase/**
teewon:
  getewayUrl: http://60.10.63.199:3307
  appId: 808a2848882e41eb9eca8b6546b81456
  appKey: 8b503d9a1d865c3c
  tenantId: E000056
  branchCode: LF00001
open:
  chain:
    saveUrl: http://47.75.189.95:5020/bus/chain/save
    appId: pig
    appsecret: pig
logging:
  level:
    com.cloud.edu.bus.mapper: debug